name: Mail on Push
 
on:
  push:
    branches:
      - main
 
jobs:
  send-mail:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
     
    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: "Push to Repository: ${{ github.repository }}"
        to: "giuliano.lember@gmail.com"
        body: |
          Kehtestuse looja nimi: ${{ github.event.pusher.name }}
          Kehtestuse sõnum: ${{ github.event.head_commit.message }}
        from: Github actions